### PR TITLE
Fix: Fix signin problem on Vercel Preview environment

### LINKED ISSUE #326: Cannot copy an invitation link on mobiles and tablets
## Description

Cannot copy an invitation link on mobiles and tablets, while it works on desktop. This issue happens both on iOS and Android.

## Notes

-

### PR DESCRIPTION
**Pull request by nick-y-ito**
## Overview 

This PR fixes issue #338, which causes sign-in failure.

## Changes

- Created `scripts/setupEnv.mjs`
- Modified the `postinstall` script in `package.json`

## Review points

- I have confirmed that the creation of `.env.development.local` file was skipped correctly on my Vercel account.

image

## References

- [Vercel - System Environment Variables Overview](https://vercel.com/docs/projects/environment-variables/system-environment-variables)
- [Vercel - Environment Variable Load Order](https://nextjs.org/docs/app/building-your-application/configuring/environment-variables#environment-variable-load-order)
- [Vercel - Environment Variable Load Order](https://nextjs.org/docs/app/building-your-application/configuring/environment-variables#environment-variable-load-order)

> ## Environment Variable Load Order
> Environment variables are looked up in the following places, in order, stopping once the variable is found.
> 
> 1. process.env
> 2. .env.$(NODE_ENV).local
> 3. .env.local (Not checked when NODE_ENV is test.)
> 4. .env.$(NODE_ENV)
> 5. .env
> 
> For example, if NODE_ENV is development and you define a variable in both .env.development.local and .env, the value in .env.development.local will be used.

## Notes

- This PR closes #326 

## Assignee Checklist:

- [x] The naming convention of the PR title is correct (See the comment at the top of this template)
- [x] The base branch is correct (See: [Types of Branches](https://github.com/nishiki-tech/nishiki-frontend/blob/develop/docs/CONTRIBUTING.md#types-of-branches))
- [x] The branch name follows the [Branch Naming Conventions](https://github.com/nishiki-tech/nishiki-frontend/blob/develop/docs/CONTRIBUTING.md#branch-naming-conventions)
- [x] The correct assignees and reviewers have been designated for this PR
- [x] The coding style follows the [Coding Style Guide](https://github.com/nishiki-tech/nishiki-frontend/blob/develop/docs/STYLEGUIDE.md)
- [x] All the related issues are associated with this PR
- [x] All criteria in the associated issues are met (please tick the checkboxes)
- [x] My changes do not generate new warnings or errors (especially in the console)

## Reviewer Checklist:

- [ ] Double-check the "Assignee Checklist"
- [ ] The code follows the generic best practices and our [Coding Style Guide](https://github.com/nishiki-tech/nishiki-frontend/blob/develop/docs/STYLEGUIDE.md)
- [ ] The code is well-commented and easy to understand
- [ ] The UI changes accurately reflect the provided design

### CODE REVIEW

**Comment by nick-y-ito** [comment]
@kotaaaa @ShoeheyOt 
Could you please review this PR when you have a moment?

**Comment by nick-y-ito** [comment]
Closes #326

**Review by kotaaaa — APPROVED** [review]
LGTM!

**Comment by nick-y-ito** [comment]
@kotaaaa 
Thank you for your review!

**Pull request merged**
