### PR TITLE
Docs: Refine `README.md`

### PR DESCRIPTION
**Pull request by nick-y-ito**
## Overview

Refines the `README.md` as much as possible.

## Changes

Please see the criteria section of the linked issues.

## Review points

- Is there anything wrong or missing?
- Looking good in both light/dark modes?
- Are the image file locations OK?
- Is there anything else you think it would be even better to add? Such as, "features" section.

## References

I was inspired by the following repositories to refine our `README.md`.
- Community & Contributing: https://github.com/vercel/next.js
- Introduction & Authors: https://github.com/radix-ui/primitives
- Tech Stack: https://github.com/andasan/cornermail_playground#stack

## Notes

- You can see the updated version of `README.md` here:
https://github.com/nishiki-tech/nishiki-frontend/blob/refs/heads/docs/279-refine-readmemd/README.md

## Assignee Checklist:

- [x] The naming convention of the PR title is correct (See the comment at the top of this template)
- [x] The base branch is correct (See: [Types of Branches](https://github.com/nishiki-tech/nishiki-frontend/blob/develop/docs/CONTRIBUTING.md#types-of-branches))
- [x] The branch name follows the [Branch Naming Conventions](https://github.com/nishiki-tech/nishiki-frontend/blob/develop/docs/CONTRIBUTING.md#branch-naming-conventions)
- [x] The correct assignees and reviewers have been designated for this PR
- [x] The coding style follows the [Coding Style Guide](https://github.com/nishiki-tech/nishiki-frontend/blob/develop/docs/STYLEGUIDE.md)
- [x] All the related issues are associated with this PR
- [x] All criteria in the associated issues are met (please tick the checkboxes)
- [x] My changes do not generate new warnings or errors (especially in the console)

## Reviewer Checklist:

- [ ] Double-check the "Assignee Checklist"
- [ ] The code follows the generic best practices and our [Coding Style Guide](https://github.com/nishiki-tech/nishiki-frontend/blob/develop/docs/STYLEGUIDE.md)
- [ ] The code is well-commented and easy to understand
- [ ] The UI changes accurately reflect the provided design

### CODE REVIEW

**Review by hitohata — APPROVED** [review]
I feel the images should be better placed after the title section.
This is my personal opinion though. Therefore, I approved this PR.

**Comment by nick-y-ito** [comment]
@hitohata Thank you for your feedback and approval!

What you mean is something like this?

image

**Comment by nick-y-ito** [comment]
@hitohata 

I was inspired by [`Radix UI's README.md`](https://github.com/radix-ui/primitives) for the top part, by the way.

**Review by kotaaaa — APPROVED** [review]
LGTM, thanks!

**Comment by nick-y-ito** [comment]
@hitohata 

> I feel the images (not an icon) should be better placed after the title section.

https://github.com/nishiki-tech/nishiki-frontend/blob/refs/heads/docs/279-refine-readmemd/README.md

As you suggested, I have restructured the intro part! This looks nicer 😄

**Comment by nick-y-ito** [comment]
I added a [Documentaion](https://github.com/nishiki-tech/nishiki-frontend/blob/refs/heads/docs/279-refine-readmemd/README.md#documentation) section!

**Comment by nick-y-ito** [comment]
Also added the backend members to the authors list!

https://github.com/nishiki-tech/nishiki-frontend/blob/refs/heads/docs/279-refine-readmemd/README.md#authors

**Review by kanta1207 — APPROVED** [review]
Sorry for the late approval... I thought I already approved it, but somehow didn't!
It's looking beautiful! Thank you for the arrangement!!

**Comment by nick-y-ito** [comment]
@hitohata @kotaaaa @kanta1207

Thank you for taking the time for your reviews! I hope this `README.md` will attract many visitors 😄

**Pull request merged**
