### PR TITLE
Feature: Set up App icons & Web Manifest

### PR DESCRIPTION
**Pull request by nick-y-ito**
## Overview

This PR introduces our LOGO everywhere, such as favicon, touch icon, and OG image.

## Changes

- Set up favicon
  - Added `public/images/icons/favicon.ico`
  - Specified it for `icons` property in `layout.tsx`
- Set up OGP
  - Added `public/images/og.png`
  - Configured `openGraph` and `twitter` property in `layout.tsx` 
- Set up PWA for Apple devices
 - Added `public/images/icons/apple-touch-icon.png`
 - Specified it for `icons` property in `layout.tsx`
 - Specified the `viewport.themeColor` in `layout.tsx`
- Set up PWA for Other devices (`manifest.ts`)
 - Added all the icon images in `public/images/icons/manifest/`
 - Created `manifest.ts`
   - Configured `shortcuts` for installation display (See the video below)
   - Specified `maskable` and `any` icons to `icons` property
- Added the `appConst.ts` and configured the app information

## Review points

Sorry for the large quantity of changed files, but there are only three files that you need to focus on for a review:
- src/app/layout.tsx
- src/app/manifest.ts
- src/const/appConst.ts

Other files are just image modifications or directory refactoring.

### Favicon (on Google Chrome of MacBook)
image<br>
image<br>

### Favicon (on Google Safari of MacBook)
image<br>
image<br>
image<br>
image<br>

### Touch Icons on iPhone, Android, Mac, Windows and Linux

Screenshot 2024-03-07 at 14 06 35
image
image

### All requirements for PWA are fulfilled

Screenshot 2024-03-05 at 16 29 32

### PWA on Android

https://github.com/nishiki-tech/nishiki-frontend/assets/99148565/70343cdd-9eea-433a-8d7f-53910c34bd8c

https://github.com/nishiki-tech/nishiki-frontend/assets/99148565/55a75124-6ffa-40d9-b390-0887d7185219

### PWA with Google Chrome on MacBook

https://github.com/nishiki-tech/nishiki-frontend/assets/99148565/ad5bd8a7-55d9-4bda-b203-2e3944192df1

### Icons

- [Next.js - favicon, icon, and apple-icon](https://nextjs.org/docs/app/api-reference/file-conventions/metadata/app-icons)
- [Next.js - Static Assets in `public`](https://nextjs.org/docs/app/building-your-application/optimizing/static-assets)
- [Next.js - icons | Metadata Object and generateMetadata Options](https://nextjs.org/docs/app/api-reference/functions/generate-metadata#icons)

## Image Generators
- [SVG to ICO Converter](https://convertio.co/svg-ico/)
- [Web App Manifest Generator](https://manifest-gen.netlify.app/)
- [Round corners in image - online](https://imgonline.tools/round-corners)

### Web Manifest
- [Next.js - manifest.json](https://nextjs.org/docs/app/api-reference/file-conventions/metadata/manifest)
- [How to add a Web App Manifest and mobile-proof your site](https://medium.com/dev-channel/how-to-add-a-web-app-manifest-and-mobile-proof-your-site-450e6e485638)
- [display](https://superpwa.com/docs/article/web-app-manifest-display-modes-what-is-the-difference/)
- [MDN - background_color](https://developer.mozilla.org/en-US/docs/Web/Manifest/background_color)
- [MDN - theme_color](https://developer.mozilla.org/en-US/docs/Web/Manifest/theme_color)
- [orientation](https://zenn.dev/takumi1001/articles/809f2e5587cb8a)
- [MDN - icons | maskable](https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/How_to/Define_app_icons#support_masking)
- [Web.dev - icons | maskable](https://web.dev/learn/pwa/web-app-manifest)
- [PWA Builder - A PWA inspector](https://www.pwabuilder.com/)

### Meta Data
- [Chrome for Developers - theme-color in meta tag](https://developer.chrome.com/docs/lighthouse/pwa/themed-omnibox?utm_source=lighthouse&utm_medium=devtools)
- [Next.js - themeColor | generateViewport](https://nextjs.org/docs/app/api-reference/functions/generate-viewport#themecolor)

### Twitter Card
- [X - Card | Developer Platform](https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/abouts-cards)
- [Next.js - twitter | Metadata object](https://nextjs.org/docs/app/api-reference/functions/generate-metadata#twitter)
- [Twitter Cards: Everything you need to know](https://sproutsocial.com/insights/twitter-cards/)
- [Qiita - Twitter Card](https://qiita.com/sysi_otsuka/items/92aa2e4d80b0c389a632)

### OGP
- [Next.js - openGraph](https://nextjs.org/docs/app/api-reference/functions/generate-metadata#opengraph)
- [OGP Checker](https://web-toolbox.dev/en/tools/ogp-checker)

## Notes

-

## Assignee Checklist:

- [x] The naming convention of the PR title is correct (See the comment at the top of this template)
- [x] The base branch is correct (See: [Types of Branches](https://github.com/nishiki-tech/nishiki-frontend/blob/develop/docs/CONTRIBUTING.md#types-of-branches))
- [x] The branch name follows the [Branch Naming Conventions](https://github.com/nishiki-tech/nishiki-frontend/blob/develop/docs/CONTRIBUTING.md#branch-naming-conventions)
- [x] The correct assignees and reviewers have been designated for this PR
- [x] The coding style follows the [Coding Style Guide](https://github.com/nishiki-tech/nishiki-frontend/blob/develop/docs/STYLEGUIDE.md)
- [x] All the related issues are associated with this PR
- [x] All criteria in the associated issues are met (please tick the checkboxes)
- [x] My changes do not generate new warnings or errors (especially in the console)

## Reviewer Checklist:

- [ ] Double-check the "Assignee Checklist"
- [ ] The code follows the generic best practices and our [Coding Style Guide](https://github.com/nishiki-tech/nishiki-frontend/blob/develop/docs/STYLEGUIDE.md)
- [ ] The code is well-commented and easy to understand
- [ ] The UI changes accurately reflect the provided design

### CODE REVIEW

**Comment by nick-y-ito** [comment]
share_6139870950269145560

The look of the icon on Android is not as expected. The image should fill the entire icon.

**Comment by nick-y-ito** [comment]
@kanta1207 @ShoeheyOt @kotaaaa 
Please review this PR when you have time. Thank you!

**Comment by nick-y-ito** [comment]
@hitohata @taniguchiiqqq 
Could you also test if you can install it as PWA and the rounded icon is displayed correctly?

**Comment by ShoeheyOt** [comment]
@nick-y-ito Thank you for your work! I tried to use it on Windows, Linux laptop and iPhone. It's All LGTM :)

**Review by kanta1207 — APPROVED** [review]
It's looking beautiful! Thanks for the update 🙏

**Pull request merged**
